### ISSUE TITLE
Not able to get it working nRF24 not responding! Is it wired correctly

### ISSUE THREAD

**Issue by rossiluis22** [ebinf/lightbar2mqtt#1]
I've been trying to use this project but i'm not able to make it work i've double checked the connections and always receive 
`[Radio] nRF24 not responding! Is it wired correctly?`

i have a Wemos D1 mini Esp32 and the pin i'm picking are:

nRF24 | ESP32 mini D1
-- | --
VCC | 3V3
GND | GND
CE | I04
CSN | I05
SCK | I018
MOSI | I023
MISO | I019

am i doing it wrong?

![image](https://github.com/user-attachments/assets/089d3f52-a9a3-4379-9b58-1cd4c2d25124)
![image](https://github.com/user-attachments/assets/04bfb7b2-3348-4c6d-8e8f-f021e517ef93)

**Comment by ebinf** [comment]
From what I can see on the pinouts, your wiring should be correct. I'm no expert in SPI so I can only guess here. Maybe try swaping MISO and MOSI once or try another pin for CE. I have a Wemos D1 ESP32 laying around so I'll check if that wiring works for me :)

**Comment by rossiluis22** [comment]
I've found the issue, i was flashing using the Wemos D1mini Esp32 from Arduino IDE and changed it to ESP32 Dev Module and it worked :)

**Comment by ebinf** [comment]
Perfect :) 10 more minutes and I'd have soldered the nRF24 to my D1 :D
