### ISSUE TITLE
Incorrect connect Method Overload Called Without Username and Password

### ISSUE THREAD

**Issue by oli-19** [ebinf/lightbar2mqtt#2]
for me the MQTT connection failed with rc=5 (Not authorized) when using the PubSubClient::connect() method. The issue occurred because the wrong method overload was used, omitting the username and password parameters. This led to authentication failure with the MQTT broker. 

I changed it from:
client.connect(clientId.c_str(), String(mqttRootTopic + "/" + clientId + "/availability").c_str(), 1, true, "offline");

to:
client.connect(clientId.c_str(), mqttUser, mqttPassword, String(mqttRootTopic + "/" + clientId + "/availability").c_str(), 1, true, "offline");

and then it worked for me

I only found this using chatgpt tbh

**Comment by ebinf** [comment]
The moment I saw the name of your issue, I knew I forgot something 😄 Your are indeed totally right, username and password are not passed to PubSubClient. I'll check if the overload including username and password works for brokers without authentication and push a fix in the next hours.

Thanks a lot for pointing that out!

**Comment by ebinf** [comment]
@oli-19 Could you maybe give the latest commit a try? It _should_ work now, but I don't use authentication on my broker just yet and didn't feel like breaking my network today 😆

**Comment by frostworx** [comment]
hey @ebinf 

Thank you very much for your esp32 solution! Great work :)

I just installed your project from latest git master and can confirm mqtt authentication works fine!

**Comment by ebinf** [comment]
Thanks for your nice words and also thanks for the confirmation :) I'm closing this issue
