### ISSUE TITLE
[Feature Request] control multiple lightbar

### ISSUE THREAD

**Issue by rossiluis22** [ebinf/lightbar2mqtt#3]
First wanted to thank you for this amazing development, I'm so happy that i finally get this integrated in Home Assistant thank you! :)

I'm not sure if it’s possible, but it would be fantastic to add support for controlling multiple light bars. My wife and I both have light bars, and being able to control them simultaneously from a single NRF24 remote would be incredibly convenient having 2 entities in HA

**Comment by ebinf** [comment]
Thanks a lot, I'm really happy to hear that :)

Well, I already had that in mind when coding the framework libraries. So this shouldn't be toooo hard to implement. From a technical perspective, this is no problem at all (at least for a low number of light bars). I'm just not sure about the exact design. Let me think about an elegant solution.

**Comment by ebinf** [comment]
Version 0.2 now adds support for multiple devices ;) While I did do some tests, could you maybe give me some feedback if everything works as expected? I own just one light bar, so I might not discover some quirks.

**Comment by rossiluis22** [comment]
i tried and it worked!! :) 🎉 thank you so much!!
